name: ramp-flight


channels:
  - conda-forge
  - defaults
  - pytorch

dependencies:
  - numpy
  - scipy
  - pandas
  - scikit-learn>=0.22
  - missingno
  - matplotlib
  - seaborn
  - ipywidgets
  - joblib
  - lightgbm
  - xgboost
  - catboost
  - pytorch-cpu
  - torchvision-cpu
  - imbalanced-learn
  - pip
  
  - pip:
    - ramp-workflow==0.6.0
    - osfclient
    - optuna
    - tensorflow-cpu
    - nltk
    - wordcloud